[package]
name = "rust_lifegame"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk = { version = "0.9.6", package = "gtk4", features = ["v4_16"] }

relm4 = "0.9.1"
relm4-components = "0.9.1"

cairo-rs = "0.20.7"

tokio = { version = "1.44.1", features = ["full"]}
